import { SelectedItemWithDetails } from './InventoryCardGrid';

export interface InventoryPreset {
  id: string;
  label: string;
  icon: string; // emoji or icon name
  items: Array<{
    id: string;
    name: string;
    quantity: number;
  }>;
}

export const INVENTORY_PRESETS: InventoryPreset[] = [
  {
    id: 'house_1_bed',
    label: '1 Bed House',
    icon: '🏠',
    items: [
      { id: 'double-bed', name: 'Double Bed & Mattress', quantity: 1 },
      { id: 'wardrobe', name: 'Wardrobe (Small)', quantity: 1 },
      { id: 'bedside-table', name: 'Bedside Table', quantity: 1 },
      { id: 'chest-drawers', name: 'Chest of Drawers', quantity: 1 },
      { id: 'sofa-2-seater', name: '2 Seater Sofa', quantity: 1 },
      { id: 'coffee-table', name: 'Coffee Table', quantity: 1 },
      { id: 'tv-small', name: 'TV (up to 42")', quantity: 1 },
      { id: 'tv-stand', name: 'TV Stand', quantity: 1 },
      { id: 'dining-table-small', name: 'Dining Table (Small)', quantity: 1 },
      { id: 'dining-chair', name: 'Dining Chair', quantity: 2 },
      { id: 'fridge', name: 'Fridge', quantity: 1 },
      { id: 'washing-machine', name: 'Washing Machine', quantity: 1 },
      { id: 'microwave', name: 'Microwave', quantity: 1 },
      { id: 'medium-box', name: 'Medium Box', quantity: 15 },
      { id: 'large-box', name: 'Large Box', quantity: 10 },
    ],
  },
  {
    id: 'house_2_bed',
    label: '2 Bed House',
    icon: '🏡',
    items: [
      { id: 'single-bed', name: 'Single Bed', quantity: 1 },
      { id: 'double-bed', name: 'Double Bed & Mattress', quantity: 1 },
      { id: 'wardrobe', name: 'Wardrobe (Small)', quantity: 2 },
      { id: 'bedside-table', name: 'Bedside Table', quantity: 2 },
      { id: 'chest-drawers', name: 'Chest of Drawers', quantity: 2 },
      { id: 'sofa-3-seater', name: '3 Seater Sofa', quantity: 1 },
      { id: 'armchair', name: 'Armchair', quantity: 1 },
      { id: 'coffee-table', name: 'Coffee Table', quantity: 1 },
      { id: 'tv-small', name: 'TV (up to 42")', quantity: 1 },
      { id: 'tv-stand', name: 'TV Stand', quantity: 1 },
      { id: 'bookshelf', name: 'Bookshelf', quantity: 1 },
      { id: 'dining-table-large', name: 'Dining Table (Large)', quantity: 1 },
      { id: 'dining-chair', name: 'Dining Chair', quantity: 4 },
      { id: 'fridge-freezer', name: 'Fridge Freezer', quantity: 1 },
      { id: 'washing-machine', name: 'Washing Machine', quantity: 1 },
      { id: 'microwave', name: 'Microwave', quantity: 1 },
      { id: 'oven', name: 'Oven / Cooker', quantity: 1 },
      { id: 'medium-box', name: 'Medium Box', quantity: 20 },
      { id: 'large-box', name: 'Large Box', quantity: 15 },
    ],
  },
  {
    id: 'house_3_bed',
    label: '3 Bed House',
    icon: '🏘️',
    items: [
      { id: 'single-bed', name: 'Single Bed', quantity: 2 },
      { id: 'double-bed', name: 'Double Bed & Mattress', quantity: 1 },
      { id: 'wardrobe', name: 'Wardrobe (Small)', quantity: 2 },
      { id: 'wardrobe-large', name: 'Wardrobe (Large)', quantity: 1 },
      { id: 'bedside-table', name: 'Bedside Table', quantity: 3 },
      { id: 'chest-drawers', name: 'Chest of Drawers', quantity: 3 },
      { id: 'dressing-table', name: 'Dressing Table', quantity: 1 },
      { id: 'sofa-3-seater', name: '3 Seater Sofa', quantity: 1 },
      { id: 'armchair', name: 'Armchair', quantity: 2 },
      { id: 'coffee-table', name: 'Coffee Table', quantity: 1 },
      { id: 'tv-large', name: 'TV (43" and above)', quantity: 1 },
      { id: 'tv-stand', name: 'TV Stand', quantity: 1 },
      { id: 'bookshelf', name: 'Bookshelf', quantity: 2 },
      { id: 'sideboard', name: 'Sideboard', quantity: 1 },
      { id: 'dining-table-large', name: 'Dining Table (Large)', quantity: 1 },
      { id: 'dining-chair', name: 'Dining Chair', quantity: 6 },
      { id: 'fridge-freezer', name: 'Fridge Freezer', quantity: 1 },
      { id: 'washing-machine', name: 'Washing Machine', quantity: 1 },
      { id: 'dishwasher', name: 'Dishwasher', quantity: 1 },
      { id: 'microwave', name: 'Microwave', quantity: 1 },
      { id: 'oven', name: 'Oven / Cooker', quantity: 1 },
      { id: 'garden-bench', name: 'Garden Bench', quantity: 1 },
      { id: 'hose-reel', name: 'Hose Reel / Garden Hose', quantity: 1 },
      { id: 'ladder', name: 'Ladder', quantity: 1 },
      { id: 'bike-rack', name: 'Bike Rack', quantity: 1 },
      { id: 'medium-box', name: 'Medium Box', quantity: 30 },
      { id: 'large-box', name: 'Large Box', quantity: 25 },
      { id: 'bubble-wrap', name: 'Bubble Wrap (roll)', quantity: 4 },
      { id: 'packing-paper', name: 'Packing Paper', quantity: 2 },
      { id: 'packing-tape', name: 'Packing Tape', quantity: 5 },
      { id: 'moving-blankets', name: 'Moving Blankets / Furniture Blankets', quantity: 8 },
      { id: 'mattress-cover', name: 'Mattress Cover', quantity: 3 },
      { id: 'sofa-cover', name: 'Sofa / Furniture Cover', quantity: 2 },
    ],
  },
  {
    id: 'house_4_bed',
    label: '4 Bed House',
    icon: '🏘️',
    items: [
      { id: 'single-bed', name: 'Single Bed', quantity: 2 },
      { id: 'double-bed', name: 'Double Bed & Mattress', quantity: 2 },
      { id: 'wardrobe', name: 'Wardrobe (Small)', quantity: 2 },
      { id: 'wardrobe-large', name: 'Wardrobe (Large)', quantity: 2 },
      { id: 'bedside-table', name: 'Bedside Table', quantity: 4 },
      { id: 'chest-drawers', name: 'Chest of Drawers', quantity: 4 },
      { id: 'dressing-table', name: 'Dressing Table', quantity: 1 },
      { id: 'sofa-3-seater', name: '3 Seater Sofa', quantity: 1 },
      { id: 'corner-sofa', name: 'Corner Sofa', quantity: 1 },
      { id: 'armchair', name: 'Armchair', quantity: 2 },
      { id: 'coffee-table', name: 'Coffee Table', quantity: 1 },
      { id: 'tv-large', name: 'TV (43\" and above)', quantity: 2 },
      { id: 'tv-stand', name: 'TV Stand', quantity: 1 },
      { id: 'bookshelf', name: 'Bookshelf', quantity: 2 },
      { id: 'sideboard', name: 'Sideboard', quantity: 1 },
      { id: 'display-cabinet', name: 'Display Cabinet', quantity: 1 },
      { id: 'dining-table-large', name: 'Dining Table (Large)', quantity: 1 },
      { id: 'dining-chair', name: 'Dining Chair', quantity: 6 },
      { id: 'fridge-freezer', name: 'Fridge Freezer', quantity: 1 },
      { id: 'washing-machine', name: 'Washing Machine', quantity: 1 },
      { id: 'dishwasher', name: 'Dishwasher', quantity: 1 },
      { id: 'microwave', name: 'Microwave', quantity: 1 },
      { id: 'oven', name: 'Oven / Cooker', quantity: 1 },
      { id: 'garden-table', name: 'Garden Table', quantity: 1 },
      { id: 'garden-chair', name: 'Garden Chair', quantity: 4 },
      { id: 'garden-bench', name: 'Garden Bench', quantity: 1 },
      { id: 'sun-lounger', name: 'Sun Lounger / Deck Chair', quantity: 2 },
      { id: 'parasol', name: 'Parasol / Garden Umbrella', quantity: 1 },
      { id: 'hose-reel', name: 'Hose Reel / Garden Hose', quantity: 1 },
      { id: 'wheelbarrow', name: 'Wheelbarrow', quantity: 1 },
      { id: 'ladder', name: 'Ladder', quantity: 1 },
      { id: 'bike-rack', name: 'Bike Rack', quantity: 1 },
      { id: 'medium-box', name: 'Medium Box', quantity: 30 },
      { id: 'large-box', name: 'Large Box', quantity: 25 },
    ],
  },
  {
    id: 'house_5_bed',
    label: '5+ Bed House',
    icon: '🏰',
    items: [
      { id: 'single-bed', name: 'Single Bed', quantity: 3 },
      { id: 'double-bed', name: 'Double Bed & Mattress', quantity: 2 },
      { id: 'king-bed', name: 'King Size Bed & Mattress', quantity: 1 },
      { id: 'wardrobe', name: 'Wardrobe (Small)', quantity: 3 },
      { id: 'wardrobe-large', name: 'Wardrobe (Large)', quantity: 3 },
      { id: 'bedside-table', name: 'Bedside Table', quantity: 6 },
      { id: 'chest-drawers', name: 'Chest of Drawers', quantity: 5 },
      { id: 'dressing-table', name: 'Dressing Table', quantity: 2 },
      { id: 'sofa-3-seater', name: '3 Seater Sofa', quantity: 1 },
      { id: 'corner-sofa', name: 'Corner Sofa', quantity: 1 },
      { id: 'armchair', name: 'Armchair', quantity: 3 },
      { id: 'coffee-table', name: 'Coffee Table', quantity: 2 },
      { id: 'tv-large', name: 'TV (43\" and above)', quantity: 2 },
      { id: 'tv-stand', name: 'TV Stand', quantity: 2 },
      { id: 'bookshelf', name: 'Bookshelf', quantity: 3 },
      { id: 'sideboard', name: 'Sideboard', quantity: 2 },
      { id: 'display-cabinet', name: 'Display Cabinet', quantity: 1 },
      { id: 'dining-table-large', name: 'Dining Table (Large)', quantity: 1 },
      { id: 'dining-chair', name: 'Dining Chair', quantity: 8 },
      { id: 'fridge-freezer', name: 'Fridge Freezer', quantity: 1 },
      { id: 'washing-machine', name: 'Washing Machine', quantity: 1 },
      { id: 'dishwasher', name: 'Dishwasher', quantity: 1 },
      { id: 'microwave', name: 'Microwave', quantity: 1 },
      { id: 'oven', name: 'Oven / Cooker', quantity: 1 },
      { id: 'garden-table', name: 'Garden Table', quantity: 1 },
      { id: 'garden-chair', name: 'Garden Chair', quantity: 6 },
      { id: 'garden-bench', name: 'Garden Bench', quantity: 1 },
      { id: 'sun-lounger', name: 'Sun Lounger / Deck Chair', quantity: 2 },
      { id: 'parasol', name: 'Parasol / Garden Umbrella', quantity: 1 },
      { id: 'outdoor-cushions', name: 'Outdoor Cushions (box / set)', quantity: 1 },
      { id: 'bbq', name: 'BBQ', quantity: 1 },
      { id: 'patio-heater', name: 'Patio Heater', quantity: 1 },
      { id: 'hose-reel', name: 'Hose Reel / Garden Hose', quantity: 1 },
      { id: 'wheelbarrow', name: 'Wheelbarrow', quantity: 1 },
      { id: 'ladder', name: 'Ladder', quantity: 1 },
      { id: 'water-butt', name: 'Water Butt / Water Barrel', quantity: 1 },
      { id: 'workbench', name: 'Workbench', quantity: 1 },
      { id: 'garage-shelving', name: 'Garage Shelving Unit', quantity: 1 },
      { id: 'tool-cabinet', name: 'Tool Cabinet (metal)', quantity: 1 },
      { id: 'bike-rack', name: 'Bike Rack', quantity: 1 },
      { id: 'pressure-washer', name: 'Pressure Washer / Compressor', quantity: 1 },
      { id: 'garden-shed-small', name: 'Garden Shed (Small)', quantity: 1 },
      { id: 'greenhouse-small', name: 'Greenhouse (Small)', quantity: 1 },
      { id: 'car-tyres', name: 'Car Tyres / Wheels (set of 4)', quantity: 1 },
      { id: 'childrens-outdoor-toys', name: 'Children\'s Outdoor Toys (trampoline / slide)', quantity: 1 },
      { id: 'medium-box', name: 'Medium Box', quantity: 40 },
      { id: 'large-box', name: 'Large Box', quantity: 30 },
    ],
  },
  {
    id: 'flat_1_bed',
    label: '1 Bed Flat',
    icon: '🏢',
    items: [
      { id: 'double-bed', name: 'Double Bed & Mattress', quantity: 1 },
      { id: 'wardrobe', name: 'Wardrobe (Small)', quantity: 1 },
      { id: 'bedside-table', name: 'Bedside Table', quantity: 1 },
      { id: 'chest-drawers', name: 'Chest of Drawers', quantity: 1 },
      { id: 'sofa-2-seater', name: '2 Seater Sofa', quantity: 1 },
      { id: 'coffee-table', name: 'Coffee Table', quantity: 1 },
      { id: 'tv-small', name: 'TV (up to 42")', quantity: 1 },
      { id: 'tv-stand', name: 'TV Stand', quantity: 1 },
      { id: 'dining-table-small', name: 'Dining Table (Small)', quantity: 1 },
      { id: 'dining-chair', name: 'Dining Chair', quantity: 2 },
      { id: 'fridge', name: 'Fridge', quantity: 1 },
      { id: 'washing-machine', name: 'Washing Machine', quantity: 1 },
      { id: 'microwave', name: 'Microwave', quantity: 1 },
      { id: 'medium-box', name: 'Medium Box', quantity: 12 },
      { id: 'large-box', name: 'Large Box', quantity: 8 },
    ],
  },
  {
    id: 'flat_2_bed',
    label: '2 Bed Flat',
    icon: '🏢',
    items: [
      { id: 'single-bed', name: 'Single Bed', quantity: 1 },
      { id: 'double-bed', name: 'Double Bed & Mattress', quantity: 1 },
      { id: 'wardrobe', name: 'Wardrobe (Small)', quantity: 2 },
      { id: 'bedside-table', name: 'Bedside Table', quantity: 2 },
      { id: 'chest-drawers', name: 'Chest of Drawers', quantity: 2 },
      { id: 'sofa-3-seater', name: '3 Seater Sofa', quantity: 1 },
      { id: 'coffee-table', name: 'Coffee Table', quantity: 1 },
      { id: 'tv-small', name: 'TV (up to 42")', quantity: 1 },
      { id: 'tv-stand', name: 'TV Stand', quantity: 1 },
      { id: 'bookshelf', name: 'Bookshelf', quantity: 1 },
      { id: 'dining-table-small', name: 'Dining Table (Small)', quantity: 1 },
      { id: 'dining-chair', name: 'Dining Chair', quantity: 4 },
      { id: 'fridge-freezer', name: 'Fridge Freezer', quantity: 1 },
      { id: 'washing-machine', name: 'Washing Machine', quantity: 1 },
      { id: 'microwave', name: 'Microwave', quantity: 1 },
      { id: 'medium-box', name: 'Medium Box', quantity: 15 },
      { id: 'large-box', name: 'Large Box', quantity: 10 },
    ],
  },
  {
    id: 'flat_3_bed',
    label: '3 Bed Flat',
    icon: '🏬',
    items: [
      { id: 'single-bed', name: 'Single Bed', quantity: 2 },
      { id: 'double-bed', name: 'Double Bed & Mattress', quantity: 1 },
      { id: 'wardrobe', name: 'Wardrobe (Small)', quantity: 3 },
      { id: 'bedside-table', name: 'Bedside Table', quantity: 3 },
      { id: 'chest-drawers', name: 'Chest of Drawers', quantity: 3 },
      { id: 'sofa-3-seater', name: '3 Seater Sofa', quantity: 1 },
      { id: 'armchair', name: 'Armchair', quantity: 1 },
      { id: 'coffee-table', name: 'Coffee Table', quantity: 1 },
      { id: 'tv-large', name: 'TV (43" and above)', quantity: 1 },
      { id: 'tv-stand', name: 'TV Stand', quantity: 1 },
      { id: 'bookshelf', name: 'Bookshelf', quantity: 1 },
      { id: 'dining-table-large', name: 'Dining Table (Large)', quantity: 1 },
      { id: 'dining-chair', name: 'Dining Chair', quantity: 6 },
      { id: 'fridge-freezer', name: 'Fridge Freezer', quantity: 1 },
      { id: 'washing-machine', name: 'Washing Machine', quantity: 1 },
      { id: 'microwave', name: 'Microwave', quantity: 1 },
      { id: 'oven', name: 'Oven / Cooker', quantity: 1 },
      { id: 'medium-box', name: 'Medium Box', quantity: 20 },
      { id: 'large-box', name: 'Large Box', quantity: 15 },
    ],
  },
  {
    id: 'flat_4_bed',
    label: '4+ Bed Flat',
    icon: '🏬',
    items: [
      { id: 'single-bed', name: 'Single Bed', quantity: 3 },
      { id: 'double-bed', name: 'Double Bed & Mattress', quantity: 2 },
      { id: 'wardrobe', name: 'Wardrobe (Small)', quantity: 4 },
      { id: 'bedside-table', name: 'Bedside Table', quantity: 4 },
      { id: 'chest-drawers', name: 'Chest of Drawers', quantity: 4 },
      { id: 'sofa-3-seater', name: '3 Seater Sofa', quantity: 1 },
      { id: 'armchair', name: 'Armchair', quantity: 2 },
      { id: 'coffee-table', name: 'Coffee Table', quantity: 1 },
      { id: 'tv-large', name: 'TV (43" and above)', quantity: 1 },
      { id: 'tv-stand', name: 'TV Stand', quantity: 1 },
      { id: 'bookshelf', name: 'Bookshelf', quantity: 2 },
      { id: 'sideboard', name: 'Sideboard', quantity: 1 },
      { id: 'dining-table-large', name: 'Dining Table (Large)', quantity: 1 },
      { id: 'dining-chair', name: 'Dining Chair', quantity: 6 },
      { id: 'fridge-freezer', name: 'Fridge Freezer', quantity: 1 },
      { id: 'washing-machine', name: 'Washing Machine', quantity: 1 },
      { id: 'dishwasher', name: 'Dishwasher', quantity: 1 },
      { id: 'microwave', name: 'Microwave', quantity: 1 },
      { id: 'oven', name: 'Oven / Cooker', quantity: 1 },
      { id: 'medium-box', name: 'Medium Box', quantity: 25 },
      { id: 'large-box', name: 'Large Box', quantity: 20 },
    ],
  },
  {
    id: 'studio',
    label: 'Studio',
    icon: '🛏️',
    items: [
      { id: 'double-bed', name: 'Double Bed & Mattress', quantity: 1 },
      { id: 'wardrobe', name: 'Wardrobe (Small)', quantity: 1 },
      { id: 'chest-drawers', name: 'Chest of Drawers', quantity: 1 },
      { id: 'sofa-2-seater', name: '2 Seater Sofa', quantity: 1 },
      { id: 'coffee-table', name: 'Coffee Table', quantity: 1 },
      { id: 'tv-small', name: 'TV (up to 42")', quantity: 1 },
      { id: 'dining-table-small', name: 'Dining Table (Small)', quantity: 1 },
      { id: 'dining-chair', name: 'Dining Chair', quantity: 2 },
      { id: 'fridge', name: 'Fridge', quantity: 1 },
      { id: 'microwave', name: 'Microwave', quantity: 1 },
      { id: 'medium-box', name: 'Medium Box', quantity: 10 },
      { id: 'large-box', name: 'Large Box', quantity: 5 },
    ],
  },
  {
    id: 'storage_unit',
    label: 'Storage Unit',
    icon: '📦',
    items: [
      { id: 'small-box', name: 'Small Box', quantity: 10 },
      { id: 'medium-box', name: 'Medium Box', quantity: 20 },
      { id: 'large-box', name: 'Large Box', quantity: 15 },
      { id: 'plastic-container', name: 'Plastic Storage Box', quantity: 5 },
    ],
  },
  {
    id: 'flatshare',
    label: 'Flatshare',
    icon: '🚪',
    items: [
      { id: 'single-bed', name: 'Single Bed', quantity: 1 },
      { id: 'wardrobe', name: 'Wardrobe (Small)', quantity: 1 },
      { id: 'chest-drawers', name: 'Chest of Drawers', quantity: 1 },
      { id: 'desk', name: 'Desk', quantity: 1 },
      { id: 'bookshelf', name: 'Bookshelf', quantity: 1 },
      { id: 'dining-chair', name: 'Dining Chair', quantity: 1 },
      { id: 'lamp-floor', name: 'Floor Lamp', quantity: 1 },
      { id: 'medium-box', name: 'Medium Box', quantity: 8 },
      { id: 'large-box', name: 'Large Box', quantity: 5 },
      { id: 'bag', name: 'Bag / Suitcase', quantity: 2 },
    ],
  },
];