/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xszrrlryxigcrkaezdgd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzenJybHJ5eGlnY3JrYWV6ZGdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzNTAyODMsImV4cCI6MjA4MTkyNjI4M30.rankfHgniM0YQIr5-fE-K-OQpVExpUFQYZWVrXBSq3w"